#
# Makefile for the I2C input drivers
#
oplus_keyboard_i2c_hid-y += i2c-hid-core.o
obj-$(CONFIG_OPLUS_I2C_HID)				+= oplus_keyboard_i2c_hid.o

oplus_keyboard_hid_pogopin-y += hid-pogopin-driver.o
obj-$(CONFIG_OPLUS_I2C_HID)				+= oplus_keyboard_hid_pogopin.o
