# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_MEMLEAK_DETECT) += oplus_bsp_memleak_detect.o

oplus_bsp_memleak_detect-y := slub_track.o vmalloc_track.o memleak_debug_stackdepot.o
