# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2021 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS_FEATURE_PMIC_MONITOR_MTK)	 += pmic_monitor.o
pmic_monitor-objs := oplus_pmic_info_get_mtk.o main.o
