# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

#ifdef OPLUS_FEATURE_SCHED_ASSIST
#obj-$(CONFIG_OPLUS_FEATURE_SCHED_ASSIST) 	+= sched_assist/
#endif /* OPLUS_FEATURE_SCHED_ASSIST */
