#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-$(CONFIG_MTK_V4L2_LENS)   += media/
obj-$(CONFIG_MTK_V4L2_LENS)   += ak7314af/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9718af/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9718/
obj-$(CONFIG_MTK_V4L2_LENS)   += lc898229/
obj-$(CONFIG_MTK_V4L2_LENS)   += gt9764/
obj-$(CONFIG_MTK_V4L2_LENS)   += gt9772a/
obj-$(CONFIG_MTK_V4L2_LENS)   += gt9772b/
obj-$(CONFIG_MTK_V4L2_LENS)   += ak7377a/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9800w/
obj-$(CONFIG_MTK_V4L2_LENS)   += ak7375c/
obj-$(CONFIG_MTK_V4L2_LENS)   += ak7375c_22823/
obj-$(CONFIG_MTK_V4L2_LENS)   += bu64253gwz/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9800v/
obj-$(CONFIG_MTK_V4L2_LENS)   += lc898217/
obj-$(CONFIG_MTK_V4L2_LENS)   += ak7314_22021/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9718p_22021/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9718p_22017/
obj-$(CONFIG_MTK_V4L2_LENS)   += gt9769_22921/
obj-$(CONFIG_MTK_V4L2_LENS)   += ak7377_21871/
obj-$(CONFIG_MTK_V4L2_LENS)   += jd5516w_21871/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9718p_22047/
obj-$(CONFIG_MTK_V4L2_LENS)   += jd5516w_22047/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9800s_22047/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9827c_23021/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9800s_23021/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9800s_tele_23021/
obj-$(CONFIG_MTK_V4L2_LENS)   += jd5516w_23251/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9827c_23081/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9800s_23081/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9800s_tele_23081/