subdir-ccflags-$(CONFIG_MTK_PLATFORM) += -I$(srctree)/drivers/misc/mediatek/include/
subdir-ccflags-$(CONFIG_OPLUS_FEATURE_OPROJECT) += -I$(srctree)/drivers/misc/mediatek/include/
obj-$(CONFIG_OPLUS_DEVICE_IFNO)	+=  device_info.o
