# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
ifeq ($(CONFIG_OPLUS_FEATURE_PROJECTINFO), y)
obj-$(CONFIG_OPLUS_FEATURE_PROJECTINFO)	+=  boot_mode.o
endif
ifeq ($(CONFIG_OPLUS_FEATURE_PROJECTINFO), m)
obj-$(CONFIG_OPLUS_FEATURE_PROJECTINFO)	+=  gki/boot_mode.o
endif
